### ISSUE TITLE
Conflicts with emoji plugin/mention plugin?

### ISSUE THREAD

**Issue by Rosey** [ngs/draft-js-markdown-shortcuts-plugin#15]
I find when I use this plugin alongside the emoji and mention plugins, the emoji/mention plugins no longer work.

I'm not sure if the issue is with this plugin or those ones! Here's an example of what happens when I try to choose an emoji: (the picker appears but as soon as I make a selection, I get this error)
<img width="918" alt="screen shot 2017-02-22 at 3 50 33 pm" src="https://cloud.githubusercontent.com/assets/1326431/23238414/b4b76ed2-f916-11e6-9465-361855b132b2.png">

Sorry, the stack is a bit big for my screenshot but the former image was where the error finally happens, and this image is where the call 
<img width="821" alt="screen shot 2017-02-22 at 3 52 08 pm" src="https://cloud.githubusercontent.com/assets/1326431/23238467/ef2e12d2-f916-11e6-91bd-074bc8ff4755.png">
stack begins -

**Comment by iansinnott** [comment]
I'm also seeing this issue. Maybe something in `linkStrategy.js`? Here's a dev stack trace: 

<img width="421" alt="screen shot 2017-02-27 at 1 37 02 am" src="https://cloud.githubusercontent.com/assets/3154865/23356113/8943d748-fc8d-11e6-8378-3674443934f5.png">

**Comment by mxstbr** [comment]
Can confirm, same issue here. :confused: Would love to use this, any ideas what's happening?

**Comment by Rosey** [comment]
I just updated to the latest version and I think this issue has been resolved. Anyone else want to confirm?

**Comment by iansinnott** [comment]
Working for me 👏 . Thanks
