### ISSUE TITLE
Code block seems can't be end

### ISSUE THREAD

**Issue by linonetwo** [ngs/draft-js-markdown-shortcuts-plugin#20]
![qq 20170501223209](https://cloud.githubusercontent.com/assets/3746270/25582112/0e274dca-2ebe-11e7-94ed-2b6f5aab67ee.png)

where sdfs is in a code block.

**Comment by linonetwo** [comment]
> quote seems the same

maybe should break out when pressing 'Enter' in an empty line?

**Comment by iansinnott** [comment]
Have you tried Shift+Enter?

**Comment by linonetwo** [comment]
Oh, it's kind of difficult to get this.
